### ISSUE TITLE
如何实现http://skycrab.github.io/PythonEngineer/访问？

### ISSUE THREAD

**Issue by an9er** [Skycrab/PythonEngineer#1]
请问一下。我访问http://skycrab.github.io　没有关联任何页面
为什么访问http://skycrab.github.io/PythonEngineer　可以。
是怎么配置的呢？

**Comment by Skycrab** [comment]
https://help.github.com/articles/creating-project-pages-from-the-command-line/
需要一个gh-pages分支
不好意思，一直没有注意到
